// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInterpreterList():Promise<Record<string, any>>;

export function InstallInterpreter(arg1:string):Promise<boolean>;

export function SetInterpreter(arg1:string):Promise<boolean>;

export function UnInstallInterpreter(arg1:string):Promise<boolean>;
